name: Build Desktop App

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        submodules: 'recursive'

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'  # Assurez-vous que cette version est compatible avec votre projet MAUI

    - name: Restore NuGet packages
      run: dotnet restore Dtwo.sln

    - name: Build the project
      run: dotnet build Dtwo.sln --configuration Release -f net6.0-windows10.0.19041.0

    - name: Create App Packages
      run: dotnet publish Dtwo.sln --configuration Release -f net6.0-windows10.0.19041.0 --no-build -o ./publish
