name: Build Desktop App

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        submodules: 'recursive'

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1'

    - name: Restore NuGet packages
      run: dotnet restore Dtwo.sln

    - name: Build the project
      run: dotnet build Dtwo.sln
