name: Build Desktop App

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    env:
      BUILD_FOR_WINDOWS: true
      IsUnpackaged: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: '0'
        submodules: 'recursive'

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'  # Assurez-vous que cette version est disponible

    - name: Install MAUI workload for Windows
      run: dotnet workload install maui-windows

    - name: Restore NuGet packages
      run: dotnet restore Dtwo.sln /p:BUILD_FOR_WINDOWS=true

    - name: Build the project
      run: dotnet build Dtwo.sln --configuration Release /p:UseMaui=true /p:BUILD_FOR_WINDOWS=true -p:IsUnpackaged=true

    - name: Create App Packages
      run: dotnet publish Dtwo.sln --configuration Release --framework net8.0-windows10.0.22621.0 /p:BUILD_FOR_WINDOWS=true --no-build -o ./publish -p:IsUnpackaged=true
 
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: published-app
        path: ./publish
