name: Build Desktop App

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: '0'
        submodules: 'recursive'

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'  # Assurez-vous que cette version est disponible

    - name: Install MAUI workload for Windows
      run: dotnet workload install maui-windows

    - name: Restore NuGet packages
      run: dotnet restore Dtwo.sln

    - name: Build the project
      run: |
        dotnet build Dtwo.sln --configuration Release /p:UseMaui=true

    - name: Create App Packages
      run: |
        dotnet publish Dtwo.sln --configuration Release --framework net8.0 --no-build -o ./publish

