name: Build Desktop App

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2022
    env:
      BUILD_FOR_WINDOWS: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: '0'
        submodules: 'recursive'

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'  # Assurez-vous que cette version est disponible

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-prerelease: true

    - name: Install MAUI workload for Windows
      run:  dotnet workload install maui --ignore-failed-sources 

    - name: Restore NuGet packages
      run: dotnet restore Dtwo.App.DesktopApp/Dtwo.App.DesktopApp.csproj /p:BUILD_FOR_WINDOWS=true

    - name: Build MAUI Windows
      run: msbuild Dtwo.App.DesktopApp/Dtwo.App.DesktopApp.csproj -r -p:Configuration=Release -p:RestorePackages=false
 
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: published-app
        path: ./publish
