name: Build Desktop App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: '0'
        submodules: 'recursive'

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Install MAUI workload for Windows
      run: dotnet workload install maui --ignore-failed-sources

    - name: Restore NuGet packages
      run: dotnet restore Dtwo.App.DesktopApp/Dtwo.App.DesktopApp.csproj

    - name: Build the project
      run: dotnet build Dtwo.App.DesktopApp/Dtwo.App.DesktopApp.csproj --configuration Release --no-restore

    - name: Publish MAUI App
      run: dotnet publish Dtwo.App.DesktopApp/Dtwo.App.DesktopApp.csproj -c Release -r win-x64 -o ./publish

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: published-app
        path: ./publish
